<?php

namespace Be\Plugin\Exporter;


class Excel extends Driver
{

    /**
     * @var \PHPExcel
     */
    private $handler = null;

    // 行号
    private $index = 0;

    // 输出格式 Excel5 : xls / Excel2007 : xlsx
    private $xlsType = 'Excel5';

    /**
     * 准备导出
     */
    public function start()
    {
        session_write_close();

        if (isset($this->config['time_limit']) && is_numeric($this->config['time_limit'])) {
            set_time_limit($this->config['time_limit']);
        } else {
            set_time_limit(3600);
        }

        if (isset($this->config['memory_limit'])) {
            ini_set('memory_limit', $this->config['memory_limit']);
        } else {
            ini_set('memory_limit', '1g');
        }

        header("Content-Type: application/vnd.ms-excel");

        $filename = null;
        if (isset($this->config['filename'])) {
            $filename = strtolower($this->config['filename']);
            if (strrchr($filename, '.') == 'xlsx') {
                $this->xlsType = 'Excel2007';
            }
        } else {
            $filename = date('YmdHis') . '.xls';
        }
        header('Content-Disposition: attachment; filename=' . $filename);

        $this->handler = new \PHPExcel();

        $properties = $this->handler->getProperties();
        $properties->setCreator("Be");
        $properties->setLastModifiedBy("Be");
        $properties->setTitle("Generated by Be Framework");
        $properties->setSubject("Generated by Be Framework");
        $properties->setDescription('Generated by Be Framework');
        $properties->setKeywords("Generated by Be Framework");
        $properties->setCategory("Generated by Be Framework");

        $this->handler->setActiveSheetIndex(0);

        $activeSheet = $this->handler->getActiveSheet();

        $sheetName = $filename;
        $pos = strrpos($filename, '.');
        if ($pos !== false) {
            $sheetName = substr($filename, 0, $pos);
        }

        $activeSheet->setTitle($sheetName);
    }

    /**
     * 设置表格头
     *
     * @param array $header
     */
    public function setHeader($header = [])
    {
        $this->index++;

        $activeSheet = $this->handler->getActiveSheet();

        $i = 0;
        foreach ($header as $x) {
            $cellName = \PHPExcel_Cell::stringFromColumnIndex($i). $this->index;
            $activeSheet->setCellValue($cellName, $x);
            $i++;
        }

        // 表头样式
        $style = array(
            'font' => array(
                'bold' => true
            ),
            'borders' => array(
                'bottom'     => array(
                    'style' => \PHPExcel_Style_Border::BORDER_THIN
                )
            )
        );

        $activeSheet->getStyle('A'.$this->index.':'. \PHPExcel_Cell::stringFromColumnIndex($i-1) .$this->index)->applyFromArray($style);
    }

    /**
     * 添加一行数据
     *
     * @param array $row
     */
    public function addRow($row = [])
    {
        $this->index++;

        $activeSheet = $this->handler->getActiveSheet();

        $i = 1;
        foreach ($row as $x) {
            $cellName = $i . $this->index;
            $activeSheet->setCellValue($cellName, $x);
            $i++;
        }
    }


    /**
     * 结束输出，收尾
     */
    public function end() {
        $writer = \PHPExcel_IOFactory::createWriter($this->handler, $this->xlsType);
        $writer->save('php://output');
    }

}